language: java

jdk:
  - oraclejdk8

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

before_cache:
  - rm -rf $HOME/.gradle/*
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/


after_success:
  - ./gradlew jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)
